#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# format files that have changed
pnpm exec pretty-quick --staged
# fix
pnpm exec eslint --fix . 
